# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Fengdan Ye
description: >- # this means to ignore newlines until "baseurl:"
  Data Science & Neuroimaging
baseurl: "" # the subpath of the site
url: "https://fye92.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: fengdanye@protonmail.com
      link: fengdanye@protonmail.com
  follow:
    - name: Twitter
      link: http://twitter.com/YeFengdan
      username: "@YeFengdan"
    - name: LinkedIn
      link: http://linkedin.com/in/fengdanye
    - name: GitHub
      link: http://github.com/fye92
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
